apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurearcdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azurearcdemo
  template:
    metadata:
      labels:
        app: azurearcdemo
    spec:
      containers:
      - name: azurearcdemo
        image: azureusergroup.azurecr.io/azurearcdemo:v4.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
